openapi: '3.0.2'
info:
  title: Futureday Chat
  version: '1.0'
paths:
  /user:
    post:
      description: "Add new user to application"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: OK
  /group:
    post:
      description: "Create a new Group Chat"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Group'
      responses:
        '200':
          description: OK
      
components:
  schemas:
    Group:
      required:
        - "name"
      properties:
        name:
          type: string
        description:
          type: string
    User:
      required:
        - "name"
      type: object
      properties:
        name:
          type: string