/* tslint:disable */
/* eslint-disable */
/**
 * Futureday Chat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MessageCreate
 */
export interface MessageCreate {
    /**
     * 
     * @type {string}
     * @memberof MessageCreate
     */
    body: string;
    /**
     * 
     * @type {string}
     * @memberof MessageCreate
     */
    userId: string;
}

/**
 * Check if a given object implements the MessageCreate interface.
 */
export function instanceOfMessageCreate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "body" in value;
    isInstance = isInstance && "userId" in value;

    return isInstance;
}

export function MessageCreateFromJSON(json: any): MessageCreate {
    return MessageCreateFromJSONTyped(json, false);
}

export function MessageCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'body': json['body'],
        'userId': json['userId'],
    };
}

export function MessageCreateToJSON(value?: MessageCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'body': value.body,
        'userId': value.userId,
    };
}

