/* tslint:disable */
/* eslint-disable */
/**
 * Futureday Chat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatCreate
 */
export interface ChatCreate {
    /**
     * 
     * @type {string}
     * @memberof ChatCreate
     */
    title: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ChatCreate
     */
    userIds: Array<string>;
}

/**
 * Check if a given object implements the ChatCreate interface.
 */
export function instanceOfChatCreate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "userIds" in value;

    return isInstance;
}

export function ChatCreateFromJSON(json: any): ChatCreate {
    return ChatCreateFromJSONTyped(json, false);
}

export function ChatCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'userIds': json['userIds'],
    };
}

export function ChatCreateToJSON(value?: ChatCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'userIds': value.userIds,
    };
}

