/* tslint:disable */
/* eslint-disable */
/**
 * Futureday Chat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Message
 */
export interface Message {
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    body: string;
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    chatId: string;
    /**
     * 
     * @type {Date}
     * @memberof Message
     */
    createdAtUtc: Date;
}

/**
 * Check if a given object implements the Message interface.
 */
export function instanceOfMessage(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "body" in value;
    isInstance = isInstance && "userId" in value;
    isInstance = isInstance && "chatId" in value;
    isInstance = isInstance && "createdAtUtc" in value;

    return isInstance;
}

export function MessageFromJSON(json: any): Message {
    return MessageFromJSONTyped(json, false);
}

export function MessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): Message {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'body': json['body'],
        'userId': json['userId'],
        'chatId': json['chatId'],
        'createdAtUtc': (new Date(json['createdAtUtc'])),
    };
}

export function MessageToJSON(value?: Message | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'body': value.body,
        'userId': value.userId,
        'chatId': value.chatId,
        'createdAtUtc': (value.createdAtUtc.toISOString()),
    };
}

